# -*- coding: utf-8 -*-
with open('app/admin/page.tsx', 'a', encoding='utf-8') as f:
    f.write('                <h3 className="font-medium mb-4">All Products</h3>\n')
    f.write('                <div className="space-y-4">\n')
    f.write('{products.map(p=><div key={p.id} className="bg-white rounded-xl p-4 shadow-sm">\n')
    f.write('  <div className="flex gap-3">\n')
    f.write('    {p.mainImage && <img src={p.mainImage} alt="" className="w-16 h-16 object-cover rounded" />}\n')
    f.write('    <div>\n')
    f.write('      <h4 className="font-medium">{p.name}</h4>\n')
    f.write('      <p className="text-sm text-gray-500">{p.categoryName}</p>\n')
    f.write('      <p className="text-sm text-[#C9A96E]">EUR {p.price}</p>\n')
    f.write('      <p className="text-xs text-gray-400">{p.specs?.length || 0} specs | {p.detailImages?.length || 0} details</p>\n')
    f.write('    </div>\n')
    f.write('  </div>\n')
    f.write('  <div className="flex gap-2 mt-3">\n')
    f.write('    <button onClick={()=>edit(p)} className="flex-1 py-1 text-sm border rounded hover:bg-gray-50">Edit</button>\n')
    f.write('    <button onClick={()=>del(p.id)} className="flex-1 py-1 text-sm border rounded hover:bg-gray-50 text-red-500">Delete</button>\n')
    f.write('  </div>\n')
    f.write('</div>)}\n')
    f.write('</div>\n')
    f.write('              </div>\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        )}\n')
    f.write('      </main>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
