with open('app/admin/page.tsx', 'a', encoding='utf-8') as f:
    f.write('((img,i)=><div key={i} className="relative group"><img src={img} alt="" className="w-full aspect-square object-cover rounded" /><button onClick={()=>removeDetailImage(i)} className="absolute top-1 right-1 bg-red-500 text-white w-6 h-6 rounded-full text-xs opacity-0 group-hover:opacity-100">X</button></div>))}</div>\n')
    f.write('                </div>\n')
    f.write('                \n')
    f.write('                <button onClick={saveProduct} className="w-full bg-[#C9A96E] text-white py-3 rounded-xl font-medium">{newP.id ? \'Update\' : \'Save\'} Product</button>\n')
    f.write('              </div>\n')
    f.write('              \n')
    f.write('              <div>\n')
    f.write('                <h3 className="font-medium mb-4">All Products</h3>\n')
    f.write('                <div className="space-y-4">')
    f.write('{products.map(p=><div key={p.id} className="bg-white rounded-xl p-4 shadow-sm"><div className="flex gap-3">')
    f.write('{p.mainImage && <img src={p.mainImage} alt="" className="w-16 h-16 object-cover rounded" />}')
    f.write('<div><h4 className="font-medium">{p.name}</h4><p className="text-sm text-gray-500">{p.categoryName}</p><p className="text-sm text-[#C9A96E]">EUR {p.price}</p></div></div>')
    f.write('<div className="flex gap-2 mt-3"><button onClick={()=>editProduct(p)} className="flex-1 py-1 text-sm border rounded hover:bg-gray-50">Edit</button><button onClick={()=>deleteProduct(p.id)} className="flex-1 py-1 text-sm border rounded hover:bg-gray-50 text-red-500">Delete</button></div></div>)}')
    f.write('</div>\n')
    f.write('              </div>\n')
    f.write('            </div>\n')
    f.write('          </div>\n')
    f.write('        )}\n')
    f.write('      </main>\n')
    f.write('    </div>\n')
    f.write('  );\n')
    f.write('}\n')
