with open('app/admin/page.tsx', 'a', encoding='utf-8') as f:
    f.write('\n            <button onClick={saveCfg} className="mt-4 bg-[#C9A96E] text-white px-6 py-3 rounded-lg">Save</button>\n')
    f.write('          </div>\n')
    f.write('        )}\n')
    f.write('        \n')
    f.write('        {tab === "products" && (\n')
    f.write('          <div>\n')
    f.write('            <div className="flex justify-between items-center mb-6">\n')
    f.write('              <h2 className="text-2xl font-light">Manage Products</h2>\n')
    f.write('              <button onClick={resetForm} className="px-4 py-2 border rounded-lg hover:bg-gray-50">+ New</button>\n')
    f.write('            </div>\n')
    f.write('            <div className="grid lg:grid-cols-3 gap-8">\n')
    f.write('              <div className="lg:col-span-2 space-y-6">\n')
    f.write('                <div className="bg-white rounded-xl p-6 shadow-sm">\n')
    f.write('                  <h3 className="font-medium mb-4">Basic Info</h3>\n')
    f.write('                  <div className="grid grid-cols-3 gap-4 mb-4">\n')
    f.write('                    <div><label className="text-sm text-gray-600">Name *</label><input value={newP.name||\'\'} onChange={e=>setNewP({...newP,name:e.target.value})} className="w-full p-2 border rounded" /></div>\n')
    f.write('                    <div><label className="text-sm text-gray-600">Category</label><select value={newP.category||\'clothing\'} onChange={e=>setNewP({...newP,category:e.target.value})} className="w-full p-2 border rounded"><option value="clothing">Clothing</option><option value="pants">Pants</option><option value="bags">Bags</option><option value="watches">Watches</option><option value="jewelry">Jewelry</option></select></div>\n')
    f.write('                    <div><label className="text-sm text-gray-600">Price EUR *</label><input type="number" value={newP.price||\'\'} onChange={e=>setNewP({...newP,price:Number(e.target.value)})} className="w-full p-2 border rounded" /></div>\n')
    f.write('                  </div>\n')
    f.write('                  <div><label className="text-sm text-gray-600">Description</label><textarea value={newP.description||\'\'} onChange={e=>setNewP({...newP,description:e.target.value})} className="w-full p-2 border rounded h-20" /></div>\n')
    f.write('                </div>\n')
    f.write('                \n')
    f.write('                <div className="bg-white rounded-xl p-6 shadow-sm">\n')
    f.write('                  <h3 className="font-medium mb-4">Main Image</h3>\n')
    f.write('                  <div onDragOver={e=>e.preventDefault()} onDrop={e=>handleDrop(e,\'mainImage\')} onClick={()=>document.getElementById(\'mainImageInput\')?.click()} className="w-full h-40 border-2 border-dashed rounded-lg flex items-center justify-center cursor-pointer hover:border-[#C9A96E]">\n')
    f.write('                    {newP.mainImage ? <img src={newP.mainImage} alt="" className="h-36 object-contain" /> : <span className="text-gray-400">Drop or click</span>}\n')
    f.write('                  </div>\n')
    f.write('                  <input id="mainImageInput" type="file" accept="image/*" onChange={e=>handleFileUpload(e,\'mainImage\')} className="hidden" />\n')
    f.write('                </div>\n')
    f.write('                \n')
    f.write('                <div className="bg-white rounded-xl p-6 shadow-sm">\n')
    f.write('                  <h3 className="font-medium mb-4">Spec Images (Color + Size)</h3>\n')
    f.write('                  <div className="grid grid-cols-4 gap-4 mb-4">\n')
    f.write('                    <div><label className="text-sm text-gray-600">Color</label><select value={newSpec.color} onChange={e=>setNewSpec({...newSpec,color:e.target.value})} className="w-full p-2 border rounded"><option value="">Select</option>')
    for c in ["White", "Black", "Beige", "Brown", "Navy", "Red", "Pink", "Green", "Blue", "Yellow", "Gray", "Gold", "Silver"]:
        f.write(f'<option value="{c}">{c}</option>')
    f.write('</select></div>\n')
    f.write('                    <div><label className="text-sm text-gray-600">Size</label><select value={newSpec.size} onChange={e=>setNewSpec({...newSpec,size:e.target.value})} className="w-full p-2 border rounded"><option value="">Select</option>')
    for s in ["XS", "S", "M", "L", "XL", "XXL"]:
        f.write(f'<option value="{s}">{s}</option>')
    f.write('</select></div>\n')
    f.write('                    <div><label className="text-sm text-gray-600">Stock</label><input type="number" value={newSpec.stock} onChange={e=>setNewSpec({...newSpec,stock:Number(e.target.value)})} className="w-full p-2 border rounded" /></div>\n')
    f.write('                    <div><label className="text-sm text-gray-600">Image</label><div onClick={()=>document.getElementById(\'specImageInput\')?.click()} className="p-2 border rounded cursor-pointer truncate">{newSpec.image ? \'Selected\' : \'Select\'}</div><input id="specImageInput" type="file" accept="image/*" onChange={e=>handleFileUpload(e,\'specImage\')} className="hidden" /></div>\n')
    f.write('                  </div>\n')
    f.write('                  {newSpec.image && <img src={newSpec.image} alt="" className="w-16 h-16 object-cover mb-2 rounded" />}\n')
    f.write('                  <button onClick={addSpec} className="px-4 py-2 bg-[#1A1A1A] text-white rounded">Add</button>\n')
    f.write('                  <div className="mt-4 space-y-2">{newP.specs?.map(s=><div key={s.id} className="flex items-center gap-3 p-2 bg-gray-50 rounded"><img src={s.image} alt="" className="w-12 h-12 object-cover rounded" /><span className="font-medium">{s.color}</span><span className="text-gray-500">{s.size}</span><span className="text-sm text-gray-400">x{s.stock}</span><button onClick={()=>removeSpec(s.id)} className="ml-auto text-red-500">X</button></div>)}</div>\n')
    f.write('                </div>\n')
    f.write('                \n')
    f.write('                <div className="bg-white rounded-xl p-6 shadow-sm">\n')
    f.write('                  <h3 className="font-medium mb-4">Detail Images</h3>\n')
    f.write('                  <div onDragOver={e=>e.preventDefault()} onDrop={e=>handleDrop(e,\'detailImage\')} onClick={()=>document.getElementById(\'detailImageInput\')?.click()} className="w-full h-24 border-2 border-dashed rounded-lg flex items-center justify-center cursor-pointer hover:border-[#C9A96E]">\n')
    f.write('                    <span className="text-gray-400">Drop detail images (brand, care, etc.)</span>\n')
    f.write('                  </div>\n')
    f.write('                  <input id="detailImageInput" type="file" accept="image/*" onChange={e=>handleFileUpload(e,\'detailImage\')} className="hidden" />\n')
    f.write('                  <div className="grid grid-cols-4 gap-4 mt-4">{newP.detailImages?.map