$content = @"
2 border rounded h-20 resize-none" />"@

$file = "app\admin\page.tsx"
Add-Content -Path $file -Value $content
Add-Content -Path $file -Value ""
Add-Content -Path $file -Value "              <button onClick={addPro} className='bg-[#1A1A1A] text-white px-6 py-3 rounded-lg hover:bg-[#C9A96E] transition'>Add Product</button>"
Add-Content -Path $file -Value "            </div>"
Add-Content -Path $file -Value ""
Add-Content -Path $file -Value "            <div className='grid grid-cols-3 gap-4'>"
Add-Content -Path $file -Value "              {products.map((p) => ("
Add-Content -Path $file -Value "                <div key={p.id} className='bg-white rounded-xl p-4 shadow-sm'>"
Add-Content -Path $file -Value "                  {p.image && <img src={p.image} alt={p.name} className='w-full aspect-square object-cover mb-3 rounded' />}"
Add-Content -Path $file -Value "                  <h3 className='font-medium'>{p.name}</h3>"
Add-Content -Path $file -Value "                  <p className='text-sm text-gray-500'>{p.categoryName}</p>"
Add-Content -Path $file -Value "                  <p className='text-[#C9A96E]'>EUR {p.price}</p>"
Add-Content -Path $file -Value "                  <button onClick={() => delPro(p.id)} className='text-red-500 text-sm mt-2 hover:underline'>Delete</button>"
Add-Content -Path $file -Value "                </div>"
Add-Content -Path $file -Value "              ))}"
Add-Content -Path $file -Value "            </div>"
Add-Content -Path $file -Value "          </div>"
Add-Content -Path $file -Value "        </div>"
Add-Content -Path $file -Value "      </main>"
Add-Content -Path $file -Value "    </div>"
Add-Content -Path $file -Value "  );"
Add-Content -Path $file -Value "}"
