const fs = require('fs');
const lines = [];
lines.push('"use client";');
lines.push('import { useState, useEffect, useCallback } from "react";');
lines.push('');
lines.push('interface Spec { id: string; color: string; size: string; image: string; stock: number; }');
lines.push('interface Product { id: string; name: string; category: string; categoryName: string; price: number; currency: string; description: string; mainImage: string; specs: Spec[]; detailImages: string[]; }');
lines.push('');
lines.push('const COLORS = ["White","Black","Beige","Brown","Navy","Red","Pink","Green","Blue","Yellow","Gray","Gold","Silver"];');
lines.push('const SIZES = ["XS","S","M","L","XL","XXL"];');
lines.push('');
lines.push('export default function AdminPage() {');
lines.push('  const [tab, setTab] = useState("products");');
lines.push('  const [config, setConfig] = useState<any>({});');
lines.push('  const [products, setProducts] = useState<Product[]>([]);');
lines.push('  const [loading, setLoading] = useState(true);');
lines.push('  const [msg, setMsg] = useState("");');
lines.push('  const [uploading, setUploading] = useState(false);');
lines.push('  const [newP, setNewP] = useState<Partial<Product>>({ name: "", category: "clothing", price: 0, mainImage: "", specs: [], detailImages: [], description: "" });');
lines.push('  const [newSpec, setNewSpec] = useState<Spec>({ id: "", color: "", size: "", image: "", stock: 99 });');
lines.push('');
lines.push('  useEffect(() => { loadData(); }, []);');
lines.push('');
lines.push('  async function loadData() {');
lines.push('    const [c, p] = await Promise.all([fetch("/api/config").then((r) => r.json()), fetch("/api/products").then((r) => r.json())]);');
lines.push('    setConfig(c); setProducts(p || []); setLoading(false);');
lines.push('  }');
lines.push('');
lines.push('  async function saveCfg() {');
lines.push('    const r = await fetch("/api/config", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(config) });');
lines.push('    setMsg(r.ok ? "Saved!" : "Error"); setTimeout(() => setMsg(""), 3000);');
lines.push('  }');
lines.push('');
lines.push('  const uploadImage = useCallback(async (file: File): Promise<string> => {');
lines.push('    return new Promise((resolve, reject) => {');
lines.push('      const reader = new FileReader();');
lines.push('      reader.onload = async () => {');
lines.push('        try {');
lines.push('          const res = await fetch("/api/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ image: reader.result }) });');
lines.push('          const data = await res.json();');
lines.push('          if (data.success) resolve(data.url); else reject(new Error("Failed"));');
lines.push('        } catch { reject(new Error("Failed")); }');
lines.push('      };');
lines.push('      reader.onerror = reject;');
lines.push('      reader.readAsDataURL(file);');
lines.push('    });');
lines.push('  }, []);');
lines.push('');
lines.push('  async function handleUpload(e: React.ChangeEvent<HTMLInputElement>, target: string) {');
lines.push('    const file = e.target.files?.[0]; if (!file) return;');
lines.push('    setUploading(true);');
lines.push('    try {');
lines.push('      const url = await uploadImage(file);');
lines.push('      if (target === "main") setNewP({ ...newP, mainImage: url });');
lines.push('      else if (target === "spec") setNewSpec({ ...newSpec, image: url });');
lines.push('      else if (target === "detail") setNewP({ ...newP, detailImages: [...(newP.detailImages || []), url] });');
lines.push('      setMsg("Uploaded!");');
lines.push('    } catch { setMsg("Failed"); }');
lines.push('    setUploading(false); setTimeout(() => setMsg(""), 3000);');
lines.push('  }');
lines.push('');
lines.push('  async function handleDrop(e: React.DragEvent, target: string) {');
lines.push('    e.preventDefault();');
lines.push('    const file = e.dataTransfer.files[0];');
lines.push('    if (!file?.type.startsWith("image/")) { setMsg("Image only"); setTimeout(() => setMsg(""), 3000); return; }');
lines.push('    setUploading(true);');
lines.push('    try {');
lines.push('      const url = await uploadImage(file);');
lines.push('      if (target === "main") setNewP({ ...newP, mainImage: url });');
lines.push('      else if (target === "spec") setNewSpec({ ...newSpec, image: url });');
lines.push('      else if (target === "detail") setNewP({ ...newP, detailImages: [...(newP.detailImages || []), url] });');
lines.push('      setMsg("Uploaded!");');
lines.push('    } catch { setMsg("Failed"); }');
lines.push('    setUploading(false); setTimeout(() => setMsg(""), 3000);');
lines.push('  }');
lines.push('');
lines.push('  function addSpec() {');
lines.push('    if (!newSpec.color || !newSpec.size || !newSpec.image) { setMsg("Fill all"); setTimeout(() => setMsg(""), 3000); return; }');
lines.push('    const spec = { ...newSpec, id: Date.now().toString() };');
lines.push('    setNewP({ ...newP, specs: [...(newP.specs || []), spec] });');
lines.push('    setNewSpec({ id: "", color: "", size: "", image: "", stock: 99 });');
lines.push('  }');
lines.push('');
lines.push('  function removeSpec(id: string) { setNewP({ ...newP, specs: (newP.specs || []).filter(s => s.id !== id) }); }');
lines.push('  function removeDetail(index: number) { const arr = [...(newP.detailImages || [])]; arr.splice(index, 1); setNewP({ ...newP, detailImages: arr }); }');
lines.push('');
lines.push('  async function save() {');
lines.push('    if (!newP.name || !newP.price) { setMsg("Name & price"); setTimeout(() => setMsg(""), 3000); return; }');
lines.push('    const product: Product = { ...newP as Product, id: newP.id || Date.now().toString(), categoryName: newP.category!.charAt(0).toUpperCase() + newP.category!.slice(1), currency: "EUR" };');
lines.push('    const r = await fetch("/api/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(product) });');
lines.push('    if (r.ok) { setMsg("Saved!"); setNewP({ name: "", category: "clothing", price: 0, mainImage: "", specs: [], detailImages: [], description: "" }); loadData(); }');
lines.push('    else setMsg("Error"); setTimeout(() => setMsg(""), 3000);');
lines.push('  }');
lines.push('');
lines.push('  function edit(p: Product) { setNewP(p); }');
lines.push('  async function del(id: string) { if (!confirm("Delete?")) return; await fetch("/api/products", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); loadData(); }');
lines.push('  function reset() { setNewP({ name: "", category: "clothing", price: 0, mainImage: "", specs: [], detailImages: [], description: "" }); }');
lines.push('');

fs.writeFileSync('app/admin/page.tsx', lines.join('\n'));
console.log('Part 1 done');
