export default {
  navHome: "Startseite",
  navShop: "Shop",
  navCollections: "Kollektionen",
  navWorld: "Welt",
  navJournal: "Journal",
  navContact: "Kontakt",
  heroBrand: "Maison NOREVA",
  heroSeason: "SS 2026",
  heroManifesto1: "Wir machen Dinge,",
  heroManifesto2: "die halten.",
  heroSubtext: "Kleidung ist kein Trend. Es ist eine Entscheidung.",
  heroExplore: "Entdecken",
  heroScroll: "Scrollen",
  collectionsTheObjects: "Die Objekte",
  collectionsViewAll: "Alle Ansehen",
  collectionsViewDetails: "Details Ansehen",
  collectionsTheAtelier: "Die Atelier Linie",
  collectionsAtelierTagline: "Stille Verfeinerung.",
  collectionsAtelierDesc: "Zwölf Teile. Nicht mehr.",
  collectionsLeVolume: "Le Volume Sombre",
  collectionsLeVolumeTagline: "Struktur ohne Kraft.",
  collectionsLeVolumeDesc: "Acht Silhouetten. Kompromisslos.",
  collectionsViewCollection: "Kollektion Ansehen",
  searchProducts: "Produkte suchen...",
  filters: "Filter",
  viewAll: "Alle Ansehen",
  browseCategory: "Nach Kategorie durchsuchen",
  productsTitle: "Alle Produkte",
  productsSubtitle: "Sorgfältig ausgewählt. Gemacht um zu halten.",
  productsShopAll: "Alle Ansehen",
  productsNoProducts: "Noch keine Produkte in dieser Kollektion.",
  productsBackTo: "Zurück zur Kollektion",
  productsColor: "Farbe",
  productsSize: "Größe",
  productsInquire: "VIA WHATSAPP ANFRAGEN",
  productsInStock: "Auf Lager",
  productsOutOfStock: "Nicht Verfügbar",
  productsAvailable: "verfügbar",
  productsSpecifications: "Spezifikationen",
  productsDetails: "Details",
  personalTitle: "Persönlicher Service",
  personalSubtitle: "Ihr persönlicher Stylist",
  personalSubtitle2: "ist nur eine Nachricht entfernt.",
  personalText1: "Wir glauben nicht an Einkaufswagen. Wir glauben an Gespräche.",
  personalText2: "Sagen Sie uns, was Sie suchen, und wir führen Sie.",
  personalBtn: "Gespräch Beginnen",
  personalNote: "Wir antworten innerhalb von 24 Stunden",
  journalTitle: "Journal",
  journalWorld: "Die Welt von NOREVA",
  journalRead: "Lesen",
  footerShanghaiMilan: "Shanghai — Mailand",
  footerEst: "Est. 2026",
  footerCollections: "Kollektionen",
  footerMaison: "Maison",
  footerJournal: "Journal",
  footerAtelier: "Das Atelier",
  footerSustainability: "Nachhaltigkeit",
  footerCareers: "Karriere",
  footerContact: "Kontakt",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. Alle Rechte vorbehalten.",
  footerPrivacy: "Datenschutz",
  quoteText: "Jedes Stück beginnt mit einem Gespräch.",
  quoteAuthor: "Maison NOREVA",
};
