export default {
  navHome: "Home",
  navShop: "Shop",
  navCollections: "Collections",
  navWorld: "Reviews",
  navJournal: "Carry Guides",
  navContact: "Contact",
  heroBrand: "Nayo Smart",
  heroSeason: "Urban / Business / Travel",
  heroManifesto1: "Organized for every day,",
  heroManifesto2: "refined for every journey.",
  heroSubtext: "Official Nayo Smart backpacks for commuting, business trips, travel days, and everyday carry.",
  heroExplore: "Explore",
  heroScroll: "Scroll",
  collectionsTheObjects: "Find Your Pack",
  collectionsViewAll: "View All",
  collectionsViewDetails: "View Details",
  collectionsTheAtelier: "Commuter Backpacks",
  collectionsAtelierTagline: "Daily organization with a slimmer profile.",
  collectionsAtelierDesc: "Designed for laptops, transit, office days, and city movement.",
  collectionsLeVolume: "Travel Backpacks",
  collectionsLeVolumeTagline: "More capacity, less friction.",
  collectionsLeVolumeDesc: "Purpose-built for flights, short trips, and work travel.",
  collectionsViewCollection: "View Collection",
  searchProducts: "Search backpacks...",
  filters: "Filters",
  viewAll: "View All",
  browseCategory: "Browse by use case",
  productsTitle: "All Backpacks",
  productsSubtitle: "Choose by capacity, laptop fit, travel routine, and daily carry style.",
  productsShopAll: "Shop Backpacks",
  productsNoProducts: "No products in this collection yet.",
  productsBackTo: "Back to Collection",
  productsColor: "Color",
  productsSize: "Size",
  productsInquire: "INQUIRE VIA WHATSAPP",
  productsInStock: "Available",
  productsOutOfStock: "Made to Order",
  productsAvailable: "available",
  productsSpecifications: "Specifications",
  productsDetails: "Details",
  personalTitle: "Pack Finder",
  personalSubtitle: "Not sure which backpack",
  personalSubtitle2: "fits your routine?",
  personalText1: "Tell us your laptop size, commute style, trip frequency, and ideal capacity.",
  personalText2: "We will help you choose the right Nayo Smart backpack for daily carry, business, or travel.",
  personalBtn: "Ask for a Recommendation",
  personalNote: "Replies within 24 hours",
  journalTitle: "Carry Notes",
  journalWorld: "Backpack Guides",
  journalRead: "Read Guide",
  footerShanghaiMilan: "Singapore - Global",
  footerEst: "Est. 2026",
  footerCollections: "Collections",
  footerMaison: "Brand",
  footerJournal: "Carry Guides",
  footerAtelier: "Pack Finder",
  footerSustainability: "Sustainability",
  footerCareers: "Careers",
  footerContact: "Contact",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "Copyright 2026 Nayo Smart. All rights reserved.",
  footerPrivacy: "Privacy Policy",
  quoteText: "The right backpack starts with how you move.",
  quoteAuthor: "Nayo Smart",
};
