export default {
  navShop: "Shop",
  navCollections: "Collections",
  navWorld: "Testimonials",
  navJournal: "Journal",
  navContact: "Contact",
  heroBrand: "Maison NOREVA",
  heroSeason: "SS 2026",
  heroManifesto1: "We make things",
  heroManifesto2: "that last.",
  heroSubtext: "Clothing is not a trend. It is a decision.",
  heroExplore: "Explore",
  heroScroll: "Scroll",
  collectionsTheObjects: "The Objects",
  collectionsViewAll: "View All",
  collectionsViewDetails: "View Details",
  collectionsTheAtelier: "The Atelier Line",
  collectionsAtelierTagline: "Quiet refinement.",
  collectionsAtelierDesc: "Twelve pieces. No more.",
  collectionsLeVolume: "Le Volume Sombre",
  collectionsLeVolumeTagline: "Structure without force.",
  collectionsLeVolumeDesc: "Eight silhouettes. Uncompromised.",
  collectionsViewCollection: "View Collection",
  searchProducts: "Search products...",
  filters: "Filters",
  viewAll: "View All",
  browseCategory: "Browse by category",
  productsTitle: "All Products",
  productsSubtitle: "Carefully chosen. Made to last.",
  productsShopAll: "Shop All",
  productsNoProducts: "No products in this collection yet.",
  productsBackTo: "Back to Collection",
  productsColor: "Color",
  productsSize: "Size",
  productsInquire: "INQUIRE VIA WHATSAPP",
  productsInStock: "In Stock",
  productsOutOfStock: "Out of Stock",
  productsAvailable: "available",
  productsSpecifications: "Specifications",
  productsDetails: "Details",
  personalTitle: "Personal Service",
  personalSubtitle: "Your personal stylist",
  personalSubtitle2: "is a message away.",
  personalText1: "We don't believe in shopping carts. We believe in conversations.",
  personalText2: "Tell us what you're looking for — a wardrobe, a gift, a single piece — and we will guide you.",
  personalBtn: "Begin Conversation",
  personalNote: "We respond within 24 hours",
  journalTitle: "Journal",
  journalWorld: "The World of NOREVA",
  journalRead: "Read",
  footerShanghaiMilan: "Shanghai — Milan",
  footerEst: "Est. 2026",
  footerCollections: "Collections",
  footerMaison: "Maison",
  footerJournal: "Journal",
  footerAtelier: "The Atelier",
  footerSustainability: "Sustainability",
  footerCareers: "Careers",
  footerContact: "Contact",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. All rights reserved.",
  footerPrivacy: "Privacy Policy",
  quoteText: "Each piece begins with a conversation.",
  quoteAuthor: "Maison NOREVA",
};
