export default {
  navHome: "Inicio",
  navShop: "Tienda",
  navCollections: "Colecciones",
  navWorld: "Mundo",
  navJournal: "Journal",
  navContact: "Contacto",
  heroBrand: "Maison NOREVA",
  heroSeason: "SS 2026",
  heroManifesto1: "Hacemos cosas",
  heroManifesto2: "que duran.",
  heroSubtext: "La ropa no es una tendencia. Es una decisión.",
  heroExplore: "Explorar",
  heroScroll: "Desplazar",
  collectionsTheObjects: "Los Objetos",
  collectionsViewAll: "Ver Todo",
  collectionsViewDetails: "Ver Detalles",
  collectionsTheAtelier: "La Línea Atelier",
  collectionsAtelierTagline: "Refinamiento silencioso.",
  collectionsAtelierDesc: "Doce piezas. Nada más.",
  collectionsLeVolume: "Le Volume Sombre",
  collectionsLeVolumeTagline: "Estructura sin fuerza.",
  collectionsLeVolumeDesc: "Ocho siluetas. Sin compromisos.",
  collectionsViewCollection: "Ver Colección",
  searchProducts: "Buscar productos...",
  filters: "Filtros",
  viewAll: "Ver Todo",
  browseCategory: "Explorar por categoría",
  productsTitle: "Todos los Productos",
  productsSubtitle: "Cuidadosamente elegidos. Hechos para durar.",
  productsShopAll: "Ver Todo",
  productsNoProducts: "Aún no hay productos en esta colección.",
  productsBackTo: "Volver a la Colección",
  productsColor: "Color",
  productsSize: "Talla",
  productsInquire: "CONSULTAR POR WHATSAPP",
  productsInStock: "En Stock",
  productsOutOfStock: "Agotado",
  productsAvailable: "disponible(s)",
  productsSpecifications: "Especificaciones",
  productsDetails: "Detalles",
  personalTitle: "Servicio Personal",
  personalSubtitle: "Tu estilista personal",
  personalSubtitle2: "está a un mensaje de distancia.",
  personalText1: "No creemos en carros de compra. Creemos en conversaciones.",
  personalText2: "Dinos qué buscas y te guiaremos.",
  personalBtn: "Iniciar Conversación",
  personalNote: "Respondemos en 24 horas",
  journalTitle: "Journal",
  journalWorld: "El Mundo de NOREVA",
  journalRead: "Leer",
  footerShanghaiMilan: "Shanghái — Milán",
  footerEst: "Est. 2026",
  footerCollections: "Colecciones",
  footerMaison: "Maison",
  footerJournal: "Journal",
  footerAtelier: "El Atelier",
  footerSustainability: "Sostenibilidad",
  footerCareers: "Carreras",
  footerContact: "Contacto",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. Todos los derechos reservados.",
  footerPrivacy: "Política de Privacidad",
  quoteText: "Cada pieza comienza con una conversación.",
  quoteAuthor: "Maison NOREVA",
};
