export default {
  navShop: "Boutique",
  navCollections: "Collections",
  navWorld: "Monde",
  navJournal: "Journal",
  navContact: "Contact",
  heroBrand: "Maison NOREVA",
  heroSeason: "SS 2026",
  heroTitle1: "La Nouvelle",
  heroTitle2: "Collection",
  heroExplore: "Explorer",
  heroScroll: "Défiler",
  manifestoTitle: "Nous créons des choses qui durent.",
  manifestoText: "Le vêtement n'est pas une tendance. C'est une décision. NOREVA est conçu pour ceux qui choisissent avec soin.",
  collectionsTheObjects: "Les Objets",
  collectionsViewAll: "Voir Tout",
  collectionsViewDetails: "Voir Détails",
  collectionsTheAtelier: "La Ligne Atelier",
  collectionsAtelierTagline: "Raffinement silencieux.",
  collectionsAtelierDesc: "Douze pièces. Pas plus.",
  collectionsLeVolume: "Le Volume Sombre",
  collectionsLeVolumeTagline: "Structure sans force.",
  collectionsLeVolumeDesc: "Huit silhouettes. Sans compromis.",
  collectionsViewCollection: "Voir la Collection",
  productsTitle: "Les Objets",
  productsSubtitle: "Soigneusement choisis. Faits pour durer.",
  productsShopAll: "Tout Voir",
  productsNoProducts: "Aucun produit dans cette collection.",
  productsBackTo: "Retour à la Collection",
  productsColor: "Couleur",
  productsSize: "Taille",
  productsInquire: "DEMANDER PAR WHATSAPP",
  productsInStock: "En Stock",
  productsOutOfStock: "Rupture de Stock",
  productsAvailable: "disponible(s)",
  productsSpecifications: "Spécifications",
  productsDetails: "Détails",
  personalTitle: "Service Personnel",
  personalSubtitle: "Votre styliste personnel",
  personalSubtitle2: "est à un message de distance.",
  personalText1: "Nous ne croyons pas aux paniers d'achat. Nous croyons aux conversations.",
  personalText2: "Dites-nous ce que vous cherchez et nous vous guiderons.",
  personalBtn: "Commencer la Conversation",
  personalNote: "Nous répondons sous 24 heures",
  journalTitle: "Journal",
  journalWorld: "Le Monde de NOREVA",
  journalRead: "Lire",
  footerShanghaiMilan: "Shanghai — Milan",
  footerEst: "Est. 2026",
  footerCollections: "Collections",
  footerMaison: "Maison",
  footerJournal: "Journal",
  footerAtelier: "L'Atelier",
  footerSustainability: "Durabilité",
  footerCareers: "Carrières",
  footerContact: "Contact",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. Tous droits réservés.",
  footerPrivacy: "Politique de Confidentialité",
  quoteText: "Chaque pièce commence par une conversation.",
  quoteAuthor: "Maison NOREVA",
};
