export default {
  navShop: "Negozio",
  navCollections: "Collezioni",
  navWorld: "Mondo",
  navJournal: "Journal",
  navContact: "Contatto",
  heroBrand: "Maison NOREVA",
  heroSeason: "SS 2026",
  heroManifesto1: "Creiamo cose",
  heroManifesto2: "che durano.",
  heroSubtext: "Il vestito non è una tendenza. È una decisione.",
  heroExplore: "Esplora",
  heroScroll: "Scorri",
  collectionsTheObjects: "Gli Oggetti",
  collectionsViewAll: "Vedi Tutto",
  collectionsViewDetails: "Vedi Dettagli",
  collectionsTheAtelier: "La Linea Atelier",
  collectionsAtelierTagline: "Raffinatezza silenziosa.",
  collectionsAtelierDesc: "Dodici pezzi. Niente di più.",
  collectionsLeVolume: "Le Volume Sombre",
  collectionsLeVolumeTagline: "Struttura senza forza.",
  collectionsLeVolumeDesc: "Otto silhouette. Senza compromessi.",
  collectionsViewCollection: "Vedi la Collezione",
  searchProducts: "Cerca prodotti...",
  filters: "Filtri",
  viewAll: "Vedi Tutto",
  browseCategory: "Sfoglia per categoria",
  productsTitle: "Tutti i Prodotti",
  productsSubtitle: "Scelti con cura. Fatti per durare.",
  productsShopAll: "Vedi Tutto",
  productsNoProducts: "Nessun prodotto in questa collezione.",
  productsBackTo: "Torna alla Collezione",
  productsColor: "Colore",
  productsSize: "Taglia",
  productsInquire: "RICHIEDI VIA WHATSAPP",
  productsInStock: "Disponibile",
  productsOutOfStock: "Esaurito",
  productsAvailable: "disponibile(i)",
  productsSpecifications: "Specifiche",
  productsDetails: "Dettagli",
  personalTitle: "Servizio Personale",
  personalSubtitle: "Il tuo stilista personale",
  personalSubtitle2: "è a un messaggio di distanza.",
  personalText1: "Non crediamo nei carrelli. Crediamo nelle conversazioni.",
  personalText2: "Dicci cosa stai cercando e ti guideremo.",
  personalBtn: "Inizia la Conversazione",
  personalNote: "Rispondiamo entro 24 ore",
  journalTitle: "Journal",
  journalWorld: "Il Mondo di NOREVA",
  journalRead: "Leggi",
  footerShanghaiMilan: "Shanghai — Milano",
  footerEst: "Est. 2026",
  footerCollections: "Collezioni",
  footerMaison: "Maison",
  footerJournal: "Journal",
  footerAtelier: "L'Atelier",
  footerSustainability: "Sostenibilità",
  footerCareers: "Carriere",
  footerContact: "Contatto",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. Tutti i diritti riservati.",
  footerPrivacy: "Informativa sulla Privacy",
  quoteText: "Ogni pezzo inizia con una conversazione.",
  quoteAuthor: "Maison NOREVA",
};
