export default {
  navHome: "首页",
  navShop: "商城",
  navCollections: "系列",
  navWorld: "用户评价",
  navJournal: "背包指南",
  navContact: "联系我们",
  heroBrand: "Nayo Smart",
  heroSeason: "通勤 / 商务 / 出行",
  heroManifesto1: "为有序收纳而设计，",
  heroManifesto2: "为高效移动而打磨。",
  heroSubtext: "官方 Nayo Smart 背包，适合通勤、商务差旅、城市出行与日常随身收纳。",
  heroExplore: "立即探索",
  heroScroll: "向下查看",
  collectionsTheObjects: "找到适合你的背包",
  collectionsViewAll: "查看全部",
  collectionsViewDetails: "查看详情",
  collectionsTheAtelier: "通勤背包",
  collectionsAtelierTagline: "更轻巧，更适合每天使用。",
  collectionsAtelierDesc: "为电脑通勤、办公室、地铁和城市移动场景而设计。",
  collectionsLeVolume: "旅行背包",
  collectionsLeVolumeTagline: "更大容量，更少负担。",
  collectionsLeVolumeDesc: "适合航班、短途差旅和高频出行。",
  collectionsViewCollection: "查看系列",
  searchProducts: "搜索背包...",
  filters: "筛选",
  viewAll: "查看全部",
  browseCategory: "按场景浏览",
  productsTitle: "全部背包",
  productsSubtitle: "按容量、电脑尺寸、出行需求与日常风格选择合适的背包。",
  productsShopAll: "选购背包",
  productsNoProducts: "该系列暂时还没有产品。",
  productsBackTo: "返回系列",
  productsColor: "颜色",
  productsSize: "规格",
  productsInquire: "通过 WhatsApp 咨询",
  productsInStock: "可咨询购买",
  productsOutOfStock: "支持预订",
  productsAvailable: "可选",
  productsSpecifications: "规格参数",
  productsDetails: "产品详情",
  personalTitle: "背包推荐",
  personalSubtitle: "还不确定哪款背包",
  personalSubtitle2: "更适合你的日常？",
  personalText1: "告诉我们你的电脑尺寸、通勤方式、出行频率和理想容量。",
  personalText2: "我们会帮你从日常通勤、商务和旅行需求中匹配最适合的 Nayo Smart 背包。",
  personalBtn: "获取推荐",
  personalNote: "通常 24 小时内回复",
  journalTitle: "背包笔记",
  journalWorld: "背包指南",
  journalRead: "阅读指南",
  footerShanghaiMilan: "Singapore - Global",
  footerEst: "Est. 2026",
  footerCollections: "系列",
  footerMaison: "品牌",
  footerJournal: "背包指南",
  footerAtelier: "背包推荐",
  footerSustainability: "可持续",
  footerCareers: "合作机会",
  footerContact: "联系",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "Copyright 2026 Nayo Smart. All rights reserved.",
  footerPrivacy: "隐私政策",
  quoteText: "真正合适的背包，要从你的移动方式开始。",
  quoteAuthor: "Nayo Smart",
};
