export default {
  navHome: "首页",
  navShop: "商店",
  navCollections: "系列",
  navWorld: "世界",
  navJournal: "杂志",
  navContact: "联系",
  heroBrand: "NOREVA 品牌",
  heroSeason: "SS 2026",
  heroTitle1: "全新",
  heroTitle2: "系列",
  heroExplore: "探索",
  heroScroll: "滚动",
  manifestoTitle: "我们制作经久耐用的产品。",
  manifestoText: "服装不是潮流，而是一种选择。NOREVA专为那些精心挑选、用心穿着的人士而打造。",
  collectionsTheObjects: "精选单品",
  collectionsViewAll: "查看全部",
  collectionsViewDetails: "查看详情",
  collectionsTheAtelier: "工坊系列",
  collectionsAtelierTagline: "静谧的精致。",
  collectionsAtelierDesc: "十二件。仅此而已。",
  collectionsLeVolume: "暗黑音量",
  collectionsLeVolumeTagline: "无力的结构。",
  collectionsLeVolumeDesc: "八个轮廓。毫不妥协。",
  collectionsViewCollection: "查看系列",
  productsTitle: "精选单品",
  productsSubtitle: "精心挑选，经久耐用。",
  productsShopAll: "全部",
  productsNoProducts: "该系列暂无产品。",
  productsBackTo: "返回系列",
  productsColor: "颜色",
  productsSize: "尺码",
  productsInquire: "通过微信咨询",
  productsInStock: "有货",
  productsOutOfStock: "缺货",
  productsAvailable: "可购买",
  productsSpecifications: "规格",
  productsDetails: "详情",
  personalTitle: "私人服务",
  personalSubtitle: "您的专属造型师",
  personalSubtitle2: "随时恭候您的垂询。",
  personalText1: "我们不相信购物车，我们相信对话。",
  personalText2: "告诉我们您在寻找什么——一套衣服、一份礼物、一件单品——我们将为您提供指导。",
  personalBtn: "开始对话",
  personalNote: "我们会在24小时内回复",
  journalTitle: "杂志",
  journalWorld: "NOREVA的世界",
  journalRead: "阅读",
  footerShanghaiMilan: "上海 — 米兰",
  footerEst: "创立于2026年",
  footerCollections: "系列",
  footerMaison: "品牌",
  footerJournal: "杂志",
  footerAtelier: "工坊",
  footerSustainability: "可持续发展",
  footerCareers: "加入我们",
  footerContact: "联系",
  footerWhatsApp: "微信",
  footerInstagram: "Instagram",
  footerCopyright: "© 2026 NOREVA. 保留所有权利。",
  footerPrivacy: "隐私政策",
  quoteText: "每一件作品都始于一次对话。",
  quoteAuthor: "NOREVA 品牌",
};
