export default {
  navHome: "首页",
  navShop: "商店",
  navCollections: "背包系列",
  navWorld: "客户评价",
  navJournal: "背包指南",
  navContact: "联系",
  heroBrand: "NOREVA 智能背包",
  heroSeason: "通勤 / 商务 / 旅行",
  heroManifesto1: "更聪明的收纳，",
  heroManifesto2: "为移动生活而生。",
  heroSubtext: "适合通勤、商务旅行和日常收纳的防泼水电脑背包。",
  heroExplore: "探索",
  heroScroll: "向下",
  collectionsTheObjects: "找到适合你的背包",
  collectionsViewAll: "查看全部",
  collectionsViewDetails: "查看详情",
  collectionsTheAtelier: "通勤背包",
  collectionsAtelierTagline: "轻薄、有序、适合每天出门。",
  collectionsAtelierDesc: "为电脑、通勤、骑行和城市移动设计。",
  collectionsLeVolume: "旅行背包",
  collectionsLeVolumeTagline: "更大容量，更少负担。",
  collectionsLeVolumeDesc: "适合机场、短途差旅和周末出行。",
  collectionsViewCollection: "查看系列",
  searchProducts: "搜索背包...",
  filters: "筛选",
  viewAll: "查看全部",
  browseCategory: "按场景浏览",
  productsTitle: "全部背包",
  productsSubtitle: "按容量、电脑尺寸、旅行需求和通勤场景选择智能背包。",
  productsShopAll: "购买背包",
  productsNoProducts: "该系列暂时没有产品。",
  productsBackTo: "返回系列",
  productsColor: "颜色",
  productsSize: "规格",
  productsInquire: "通过 WhatsApp 咨询",
  productsInStock: "可咨询",
  productsOutOfStock: "暂不可售",
  productsAvailable: "可选",
  productsSpecifications: "规格",
  productsDetails: "详情",
  personalTitle: "背包推荐",
  personalSubtitle: "不确定哪款背包",
  personalSubtitle2: "适合你的日常？",
  personalText1: "告诉我们你的电脑尺寸、通勤方式、旅行频率和理想容量。",
  personalText2: "我们会帮你在通勤、商务、旅行和卷盖背包之间做选择。",
  personalBtn: "获取推荐",
  personalNote: "通常 24 小时内回复",
  journalTitle: "背包指南",
  journalWorld: "NOREVA 背包指南",
  journalRead: "阅读指南",
  footerShanghaiMilan: "Shanghai",
  footerEst: "Est. 2026",
  footerCollections: "系列",
  footerMaison: "品牌",
  footerJournal: "背包指南",
  footerAtelier: "背包推荐",
  footerSustainability: "可持续",
  footerCareers: "合作",
  footerContact: "联系",
  footerWhatsApp: "WhatsApp",
  footerInstagram: "Instagram",
  footerCopyright: "Copyright 2026 NOREVA. All rights reserved.",
  footerPrivacy: "隐私政策",
  quoteText: "合适的背包，应该从你的移动方式开始。",
  quoteAuthor: "NOREVA",
};
